title: AccessDenied
description: Blog specialized on Security, Crypto and blockchain.
baseurl: "/access-denied" # the subpath of your site, e.g. /blog
url: "https://rya-sge.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url_complet: "https://rya-sge.github.io/access-denied" #image
lang: "fr_FR"
# Author
author-name:    Ryan S. 
author-image:   1.jpg
#Source : https://pixabay.com/fr/vectors/pas-d-entr√©e-signer-attention-909933/
author-job:     Security engineer | Blockchain Developer
author-email:    # Add your email for contant form.
#author-twitter: artemsheludko_ # Add your twitter account
about-author:   "Blog specialized on Security, Crypto and blockchain."

# Social settings
social-twitter:   ADCDIII
#social-facebook:
social-github:    rya-sge
#social-pinterest: artemsheludko
#social-instagram: artemsheludko_
#social-youtube:
#social-vk:
social-linkedin: ryan-sauge-045397217
repository: rya-sge/access-denied
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier:
  #https-rya-sge-github-io-access-denied  #Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown


permalink: /:year/:month/:day/:title/



plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-katex

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
